---
dist: xenial
language: python
python: 3.7
services:
  - docker

before_install:
  - bash tools/scripts/setup-env.sh
  - sudo pip install --upgrade pip setuptools tox

install: pip install tox-travis

script: tox

deploy:
  provider: script
  script: bash tools/scripts/deploy.sh
  env:
    - secure: "zvaxOechATI8/Q9QpQtnR43IbWdl6nZFFqVw/icfHkvr1hxzKLJDv3G0XGjs56VmpSc2rqTIVTLubCvCnphwJIxp4WZFr+iFCPRFvcs78PeXi/leQyreko8KVhYXLkfZM3WmZ99Ump77MMhlfH0T06opBSh7uDZ7hw9Hr57+1gOnTu8juHhDpkk0nv0wFfz2dlCUmpDQXjvmQr4d0fX4Q4fY19rTm5TY+TpphR9Tjt52IJP6gspQahzM0HfaAlFR40IJsycPMU8R3a4X9us2orYbHy3zJVxId1uniZ1K9uWMl9Wwsp+n0FDM5PkJsRe1W+E4WMT0LTVXAXYGsN80eP2CEmfCr26cBzhkn1bvuhEN7h9K+vbgxcKnYiR3H9mtOlLnSoIw/L4vea3kRAEOUzL2GuygwNvQmW+d9ZglF4UMoPLG3akmTohSki77QgWhrEqEis7u4Vfhn9S68gOa1V9EI+gEgK/M5scNrScjo4oOwmYeeJNOr1a9VAUp1BurgO1zFeDjpt1O297n2846ZVoDA8DqhswsG5Bw0yvaeQCoN4u8L4wOZ8MIUreiNhAQFWHZd11G/H86h/boCjNiJSI/JTL2tiF2bbHxDakksY1eotWMRfJynIp4YglYwEKpskHNMXHriEkz22ZY6P95ISi0HkbifWlK5vET+W+xkdg="
    - secure: "WT5mt8MEWSrOo8Xty19CIReXKQrp7tXJzWVT3YS3aRRn/7R8ra/vvqXsTawnhR9GgV74Szgk5FE0S+HVEtPOFupvEy8ltvnTgQ9i7VykhfuEy0hKmSDQatUnoCHVe+5yp3vafxrnaEta0YpGHioWlemH3zW+rS6z1p58fxi52zKZ3lFEfmtwIOQWmu1FTX+wl7t3K6nqNpj5cU5ETqx2skaP2x7cCTaV2ICpC3NQbMd1QcgDGQQ5CRXgsoLSW916CUkOtMA/6yr3kV1fe9i8Q3seH5x1isE8v+gc5kJTnf8oWW5W5Z4SSSIA06YEzLCQJVCtO4VZYuBHIcrfc+FZXl47Bhz5URqnpq7gxPd2k9FzeQc73NeqyDhNsgzBG6EqnOwX4CkSr+mFNEhKATJuZZXqYHIJeJWXMNdlHsPQJwx6x86zMMP6yDpx2uAC5rtI3ZFez/E4y3W8Bh7nSrD+5vixvUlqwbkjWvyqte/aciYJ/7Q+beRj3bYBbRvcYgUl8NAI5MwIN2qM98AVTSPykA5tXFqI22d9g1LFgsgs7iqxduYKIn5QnXqKknBSrZu6Cts0xs8Wo47tb6ChRkw0BqWvkQwrl/YuFeLGPqXtUEpZonQLkN50VGKsQF/TFao3+rbBjxM50smbRGKXGfHwE7fxC4Vg0ynHPuZa/7g9gMM="
  on:
    branch: master
